version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    filename: var/log/cowrie.log
    maxBytes: 10485760
    backupCount: 3
    formatter: default
  json:
    class: logging.FileHandler
    filename: var/log/cowrie.json
    formatter: default
root:
  level: INFO
  handlers: [file, json]
